Add orbit:cache command
ryangjchandler/orbit pull request #103
Opened 2022-03-11 10:32 UTC by jwpage

This PR adds an `orbit:cache` command which finds all non-abstract Model classes anywhere within your `app_path()` that use the Orbital trait and calls `migrate()` on them.

The only drawback I can see is that if you were including Orbital Models from Composer dependencies in `vendor` they would not be migrated by this command, but I don't know if you want to go to that level with this command.

Example output:

> No models found:
> <img width="355" alt="Screen Shot 2022-03-11 at 9 17 59 pm" src="https://user-images.githubusercontent.com/52687/157849831-9698b90d-1576-41e0-9afc-ea648967cc5e.png">
> Models found:
> <img width="360" alt="Screen Shot 2022-03-11 at 9 17 35 pm" src="https://user-images.githubusercontent.com/52687/157849840-bbc44dbf-1049-4759-a056-997943821a7f.png">

Closes #102

2022-03-13 19:45 UTC, ryangjchandler commented
Thanks for this @jwpage! Are you able to write some tests for this? Doesn't have to be anything too in-depth, just perhaps a test that executes the command and verifies that a row exists in the SQLite database?

2022-03-15 09:10 UTC, ryangjchandler requested changes

2022-03-15 09:10 UTC, ryangjchandler commented on src/Commands/CacheCommand.php
> +        $models->each(function (string $modelName): void {
```suggestion
        $models->each(function (string $model): void {
```

2022-03-15 09:10 UTC, ryangjchandler commented on src/Commands/CacheCommand.php
> +                if (class_exists($class)) {
Can we flip this around and early return instead?

2022-03-15 09:24 UTC, jwpage commented
I'll fix up those conversation points and the failing tests (I'm using an assertion not available in earlier versions of Laravel 9) and commit again. Thanks for the feedback!

2022-03-15 10:43 UTC, ryangjchandler commented
Awesome, thanks for making those changes @jwpage! I'm going to pull this down in a minute and give it a go :)

2022-03-15 10:45 UTC, ryangjchandler requested changes

2022-03-15 10:45 UTC, ryangjchandler commented on src/Commands/CacheCommand.php
> +                // Only include non-abstract Model classes that use the Oribtal trait
We can get rid of this comment, the code is clear enough I think.
```suggestion

```

2022-03-15 19:43 UTC, merged

2022-03-15 19:43 UTC, ryangjchandler commented
Thanks @jwpage, this is excellent!